version: '3.3'

services:
  elevator:
    container_name: elevator_system
    build: ./Elevator
    command: uvicorn src.api:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./Elevator:/usr/app
    ports:
      - 8000:8000
    # environment:
    #   - NUMS_FLOOR=10
    #   - NUMS_ELEVATOR=1
    #   - BASE_URL=http://127.0.0.1:8000/

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379